### PR TITLE
fix/remove-knowledge-question

### PR DESCRIPTION
**Pull request by Thomas-95IS**
## Description

Removed the knowledge-based question fields from arc section summary and contact section summary.

## Todo's before PR

- [x] Rebase from develop
- [x] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assigneses (those who'll merge)
- [x] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [x] Code syntax formatting checked
- [x] Debug messages are absent

## PR merge

Select only one:

- [x] Should be rebased.

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by GeevesH-IS** [comment]
run jenkins build

**Comment by GeevesH-IS** [comment]
run jenkins build

**Comment by GeevesH-IS** [comment]
run jenkins build

**Comment by cruddasj** [comment]
rerun jenkins build

**Comment by cruddasj** [comment]
rerun jenkins build

**Pull request merged**
