### PR TITLE
fix/review summary flags

### PR DESCRIPTION
**Pull request by LRydeard**
## Description

Changed double array into one dictionary and also hard coded a specific case within the get_comments function for eyfs and first aid having the same row identifiers (For "course" and "date" rows).

## Todo's before PR

- [ ] Rebase from develop - Requested to be pulled from Master
- [x] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [ ] Templates been checked with relevant user-story

## Migrations

- [ ] Null fields in models specifies default value
- [ ] You generated and applied migrations (`make migrate`)
- [ ] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assigneses (those who'll merge)
- [x] Specified labels
- [x] Specified milestone

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [x] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by kingainformed** [comment]
rerun jenkins build

**Comment by Thomas-95IS** [comment]
rerun jenkins build

**Comment by kingainformed** [comment]
rerun jenkins build

**Comment by kingainformed** [comment]
rerun jenkins build

**Pull request merged**
