### PR TITLE
CCN3-1561: Updates to Your personal details task

### PR DESCRIPTION
**Pull request by ricaduchateau**
## Description

- Added new review fields for the Your personal details task
- Updated the master summary page
- Updated Selenium tests
- Updated models
- Updated test migrations
- Fixed Trello bug # 106, where the Health declaration booklet summary table was duplicated on the master summary page

## Todo's before PR

- [x] Rebase from develop
- [x] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [x] Templates been checked with relevant user-story

## Migrations

- [x] Null fields in models specifies default value
- [x] You generated and applied migrations (`make migrate`)
- [x] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assignees (those who'll merge)
- [x] Specified labels
- [x] Specified milestone

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [x] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, you should be able to see the testing error discussed this morning in the log files of the failed Jenkins PR jobs.

**Comment by Thomas-95IS** [comment]
Why is this going into `release/v1.4` as opposed to  `release/v1.3`  - has there been a PROD deployment of ARC 1.3?

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, I'm not sure if there has been a v1.3 deployment of ARC, but v1.4 is at this stage just a copy of v1.3.

**Comment by Thomas-95IS** [comment]
Hi @ricaduchateau, the tests now pass. Please merge this into `v1.3.0`, as opposed to `v1.4.0` and it's good to go.

This may require you to close this PR and open another.

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, thanks for fixing this! I've changed the base branch of the PR to v1.3.0.

**Pull request merged**
