### PR TITLE
Switch Yes/No on previous registration page

### PR DESCRIPTION
**Pull request by ricaduchateau**
## Description

Switch Yes/No options on previous registration page

## Todo's before PR

- [x] Rebase from develop
- [ ] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [x] Templates been checked with relevant user-story

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assignees (those who'll merge)
- [x] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [x] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, this is indeed the fix for CCN3-1138. I did see a closed PR to fix this and that this was deployed to BUILD, but I did not see any change on the BUILD environment. I pulled develop locally and found that the issue was still present.

**Comment by Thomas-95IS** [comment]
Ah, I was looking at the wrong page - this is for the applicant themselves, right?

Although the fix should be as simple as switching around these two lines on the form, I think:

https://github.com/InformedSolutions/OFS-MORE-ARC-Website/blob/3ff62b741804245e9f902f21596045f1d54a825d/arc_application/forms/form.py#L259-L262

At least, that appears to work locally for me.

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS, this is for the ARC reviewer. The fix is indeed only switching those two lines, but PyCharm's linting functionality has formatted a load of other lines.

**Comment by ricaduchateau** [comment]
rerun jenkins build

**Pull request merged**
