### PR TITLE
Merge fix/arc-css into develop

### PR DESCRIPTION
**Pull request by ricaduchateau**
## Description

CSS cleanup for ARC view. Please see individual commit messages for more details.

## Todo's before PR

- [x] Rebase from develop
- [x] Unit tests passed (`make test`)
- [x] PR naming according our [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [x] PR description describes the overall goals of PR commits
- [x] Templates been checked with relevant user-story

## Migrations

- [x] Null fields in models specifies default value
- [x] You generated and applied migrations (`make migrate`)
- [x] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [x] Specified reviewers (even if it's yourself)
- [x] Specified assigneses (those who'll merge)
- [x] Specified labels
- [x] Specified milestone

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [ ] Should be rebased?
- [x] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

### CODE REVIEW

**Comment by cruddasj** [comment]
rerun jenkins build

**Comment by cruddasj** [comment]
It looks like the checks are failing here due to a case sensitivity mismatch on the 'Review Returned' page (as the selenium test is assuming a lower case "r" on returned). and a similar case for the Review approved page. Has the "Audit Log" link also been dropped to lower case?

**Comment by ricaduchateau** [comment]
Hi @cruddasj,

Yes, I have been adjusting the case on page and tab titles and was looking to fix them in test_selenium.py. However, my VM crashed completely and I'm struggling to get it back up. I'm currently working with Hugo to see if we can make these changes.

With kind regards,

Rica

**Comment by ricaduchateau** [comment]
Hi @cruddasj,

I've now fixed the Selenium script issues on @GeevesH-IS's laptop. I'll wait for @Thomas-95IS to complete his merge for CCN3-867 before merging this branch.

With kind regards,

Rica

**Comment by cruddasj** [comment]
rerun jenkins build

**Comment by cruddasj** [comment]
Squashing after successful selenium test execution

**Pull request merged**
